name: 'Test Selenium IDE Ubuntu'

on:
  workflow_dispatch:
jobs:
  test:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    runs-on: ubuntu-latest
    if: github.repository == 'pierrettc/selenium-ide'
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Installation de nodejs
        run: curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - &&\ apt-get install nodejs -y
      - name: Install pnpm with npm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm -r i
      - name: Build side-runner and selenium-ide
        run: npm run build
      - name: Run all tests
        run: npm run tata
